function(orbit_add_fuzz_smoke target source)
  add_executable(${target} ${source})
  target_link_libraries(${target} PRIVATE orbit::orbit)
  orbit_set_warnings(${target})
  orbit_enable_sanitizers(${target})
  if(ORBIT_BUILD_TESTS)
    add_test(NAME ${target}_smoke COMMAND ${target} ${CMAKE_CURRENT_SOURCE_DIR}/corpus)
  endif()
endfunction()
