option(ORBIT_ENABLE_ASAN "Enable AddressSanitizer" OFF)
option(ORBIT_ENABLE_UBSAN "Enable UndefinedBehaviorSanitizer" OFF)
option(ORBIT_ENABLE_TSAN "Enable ThreadSanitizer" OFF)
option(ORBIT_ENABLE_COVERAGE "Enable coverage instrumentation" OFF)

function(orbit_enable_sanitizers target)
  if(MSVC)
    return()
  endif()
  set(flags "")
  if(ORBIT_ENABLE_ASAN)
    list(APPEND flags "address")
  endif()
  if(ORBIT_ENABLE_UBSAN)
    list(APPEND flags "undefined")
  endif()
  if(ORBIT_ENABLE_TSAN)
    if(ORBIT_ENABLE_ASAN)
      message(FATAL_ERROR "TSan cannot be combined with ASan in this preset")
    endif()
    list(APPEND flags "thread")
  endif()
  if(flags)
    list(JOIN flags "," sanitizer_flags)
    target_compile_options(${target} PRIVATE -fsanitize=${sanitizer_flags} -fno-omit-frame-pointer)
    target_link_options(${target} PRIVATE -fsanitize=${sanitizer_flags})
  endif()
  if(ORBIT_ENABLE_COVERAGE)
    target_compile_options(${target} PRIVATE -O0 -g --coverage)
    target_link_options(${target} PRIVATE --coverage)
  endif()
endfunction()
